### ISSUE TITLE
Falscher Port 

### ISSUE THREAD

**Issue by ChrissT23** [Newan/ioBroker.evcc#1]
Ich habe den Adapter gestern entdeckt und installiert. Leider sucht der Adapter zumindest bei mir im falschen Port. Er nimmt den Port :80 bei mir läuft EVCC auf Port :7070 kann man das irgendwie ändern ?

**Comment by premultiply** [comment]
Der evcc Default-Port ist 7070.

**Comment by Newan** [comment]
![image](https://user-images.githubusercontent.com/3693094/169668465-1ae0a0bb-e23c-495e-8454-1452096db31e.png)
Port einfach mit angeben!
