### ISSUE TITLE
Control charging mode does not work

### ISSUE THREAD

**Issue by sash2kk** [Newan/ioBroker.evcc#12]
The control of charging modes does not work. I use 0.116.3 version of evcc and don't know if they renamed some adresses?

I try switching between "off" and "pv" mode. This is the error I get.

![image](https://user-images.githubusercontent.com/128425433/233618206-f1e2bd5f-1d88-48db-8404-be199be941bd.png)

**Comment by Newan** [comment]
works here? No Error found

**Comment by sash2kk** [comment]
How should I trigger the states? It seems to work once, but not repeating. Should I trigger the value to true? 

![grafik](https://user-images.githubusercontent.com/128425433/233853793-b5f9018b-2b16-46ad-838e-5221c02f1dc0.png)
![grafik](https://user-images.githubusercontent.com/128425433/233853844-9253f55e-5e45-47f6-8f91-8c07e271690b.png)

**Comment by Newan** [comment]
Yes set the value back to true, if necessary with Confirmed

**Comment by sash2kk** [comment]
I know what the issue is - but I don't know how to fix it.

I have 2 loadpoints in evcc. 1st one is the garage - 2nd outside. In evcc the IDs count 1 and 2. But in the evcc adapter in iobroker its counted 0 and 1.

ID 0 in iobroker is ID 1 in evcc. When I change a state in ID 0 I get the error (404)
When I change a state in iobroker ID 1 it changes the state correctly - but for ID 1 in evcc.

evcc Loadpoint 2 cannot be adressed. - So I think the problem is, that the IDs are mismatched. Any idea how to fix this?

![grafik](https://user-images.githubusercontent.com/128425433/233856542-c30d6652-73bf-4a59-a002-d1f26743ca22.png)

**Comment by Newan** [comment]
<img width="378" alt="image" src="https://user-images.githubusercontent.com/3693094/233856803-490451cd-96c2-4982-ab1a-5c21c4b3ea07.png">
Ist das auch so das unter loadpoints die falschen IDs stehen?

**Comment by sash2kk** [comment]
Genau:
![grafik](https://user-images.githubusercontent.com/128425433/233857176-e84136e8-da78-44dc-9ba5-d40cc1b3d96e.png)

**Comment by Newan** [comment]
Bitte mal alle Loadpoints löschen, Adapter neu starten. Es müsste folgende Logeinträge kommen:

"Lege neuen Ladepunkt an mit Index: " -> wenn da einer mit 0 angelegt wird, hab ich einen Bug

**Comment by sash2kk** [comment]
![grafik](https://user-images.githubusercontent.com/128425433/233862387-a6202e94-8cd4-4f48-a125-accd41a1175f.png)

Dann ist es ein Bug würde ich sagen.

**Comment by Newan** [comment]
```

evcc.0 | 2023-04-23 22:36:05.316 | info | Lege neuen Ladepunkt an mit Index: 1
-- | -- | -- | --
evcc.0 | 2023-04-23 22:36:05.316 | debug | Ladepunkt mit index loadpoint.1 gefunden...
```

Hab versucht das nachzustellen , habe aber nur einen Datenpunkt. Ist das die aktuelle Version vom git?

Node -v  = v19.7.0 (dev umgebung bei mir)

**Comment by Newan** [comment]
Durch die Zeile kann da eigentlich nie eine 0 kommen:         

[index = index + 1;// +1 why Evcc starts with 1](https://github.com/Newan/ioBroker.evcc/blob/e85a48fb5291c4edbc35fc61a9d64e5ebb63cb8c/src/main.ts#L184)

**Comment by sash2kk** [comment]
Oh Mann... ich hab keine Ahnung, wie ich eine veraltete Version vor 1 Monat installiert habe... aber irgendwie hab ich es geschafft die 0.0.4 auf dem ioBroker zu haben. Sorry - mit der 0.0.7 funktioniert es problemlos!
