### ISSUE TITLE
Feature Request: Unterstütze aller Rest API Calls 

### ISSUE THREAD

**Issue by Marty56** [Newan/ioBroker.evcc#13]
Es wäre schon, wenn der Adapter einfach alle Datenpunkte unterstützten würde, die das Rest API von EVCC anbietet.
Dann würde es keine Diskussion der Use Cases benötigt, warum ein Anwender jetzt doch den ein oder anderen Datenpunkt benötigt. Die EVCC Entwickler habe sicherlich nicht umsonst das Rest API so erweitert. 

z.B. ich fände es praktisch, wenn der vehicleOdometer als Datenpunkt auftauchen würde. Dann könnte man auf den Fahrzeugspezifischen Adapter verzichten und es gibt noch andere Beispiele

Es sollte auch konsequent darauf geachtet werden, dass zwischen Read Only, Write Only und Read Write Datenpunkten unterschieden wird.

**Comment by Newan** [comment]
Gerne PR für fehlende api calls und Verbesserungen

**Comment by Marty56** [comment]
Danke!
