### ISSUE TITLE
Feature Request: Unterstützung der Einheiten und der möglichen Werte

### ISSUE THREAD

**Issue by Marty56** [Newan/ioBroker.evcc#14]
Es wäre schön, wenn der Adapter die Einheiten, z.B. "kWh" für die chargedEnergy unterstützen würde.
Außerdem sollte der Adapter bei Werten, die nur bestimmte Werte erlauben, z.B. Phasen nur 0,1,2,3, erlauben.

Unpraktisch finde ich auch, die separaten Schalten für die Mode Umschaltung.
Besser wäre ein Mode Datenpunkt mit den erlaubten Werten off, minpv, pv und now.

**Comment by Newan** [comment]
Gerne per PR, sehe da keine prio für mich

**Comment by Newan** [comment]
Habe das gerade nochmal angesehen im Zuge von der neuen API, da die Werte dynamisch kommen, habe ich keine Units dahinter. Wenn du eine Idee hast gerne.
