### ISSUE TITLE
activePhases wird nicht aktualisiert

### ISSUE THREAD

**Issue by Marty56** [Newan/ioBroker.evcc#15]
activePhases ist 'null'.

**Comment by Marty56** [comment]
Funktioniert wohl doch. Es scheint, dass erst ein aktiver Ladevorgang stattfinden muss, damit der evcc die acitivePhases ermittelt.

**Comment by Newan** [comment]
Wurde ja mit dem #15 commit gefixed

**Comment by Marty56** [comment]
Danke. 
Ich hatte schon gedacht dass es an mir gelegen hätte.
