### ISSUE TITLE
Feature Request: Datenpunkt GET /api/tariff/<type>: list of prices 

### ISSUE THREAD

**Issue by Marty56** [Newan/ioBroker.evcc#16]
**Describe the Feature**  
Es wäre schön, wenn der Datenpunkt "tariff" vorhanden wäre.

**Comment by Newan** [comment]
`{"result":{"rates":[{"start":"2023-05-16T00:00:00+02:00","end":"2023-05-16T01:00:00+02:00","price":0.07},{"start":"2023-05-16T01:00:00+02:00","end":"2023-05-16T02:00:00+02:00","price":0.07},{"start":"2023-05-16T02:00:00+02:00","end":"2023-05-16T03:00:00+02:00","price":0.07},{"start":"2023-05-16T03:00:00+02:00","end":"2023-05-16T04:00:00+02:00","price":0.07},{"start":"2023-05-16T04:00:00+02:00","end":"2023-05-16T05:00:00+02:00","price":0.07},{"start":"2023-05-16T05:00:00+02:00","end":"2023-05-16T06:00:00+02:00","price":0.07},{"start":"2023-05-16T06:00:00+02:00","end":"2023-05-16T07:00:00+02:00","price":0.07},{"start":"2023-05-16T07:00:00+02:00","end":"2023-05-16T08:00:00+02:00","price":0.07},{"start":"2023-05-16T08:00:00+02:00","end":"2023-05-16T09:00:00+02:00","price":0.07},{"start":"2023-05-16T09:00:00+02:00","end":"2023-05-16T10:00:00+02:00","price":0.07},{"start":"2023-05-16T10:00:00+02:00","end":"2023-05-16T11:00:00+02:00","price":0.07},{"start":"2023-05-16T11:00:00+02:00","end":"2023-05-16T12:00:00+02:00","price":0.07},{"start":"2023-05-16T12:00:00+02:00","end":"2023-05-16T13:00:00+02:00","price":0.07},{"start":"2023-05-16T13:00:00+02:00","end":"2023-05-16T14:00:00+02:00","price":0.07},{"start":"2023-05-16T14:00:00+02:00","end":"2023-05-16T15:00:00+02:00","price":0.07},{"start":"2023-05-16T15:00:00+02:00","end":"2023-05-16T16:00:00+02:00","price":0.07},{"start":"2023-05-16T16:00:00+02:00","end":"2023-05-16T17:00:00+02:00","price":0.07},{"start":"2023-05-16T17:00:00+02:00","end":"2023-05-16T18:00:00+02:00","price":0.07},{"start":"2023-05-16T18:00:00+02:00","end":"2023-05-16T19:00:00+02:00","price":0.07},{"start":"2023-05-16T19:00:00+02:00","end":"2023-05-16T20:00:00+02:00","price":0.07},{"start":"2023-05-16T20:00:00+02:00","end":"2023-05-16T21:00:00+02:00","price":0.07},{"start":"2023-05-16T21:00:00+02:00","end":"2023-05-16T22:00:00+02:00","price":0.07},{"start":"2023-05-16T22:00:00+02:00","end":"2023-05-16T23:00:00+02:00","price":0.07},{"start":"2023-05-16T23:00:00+02:00","end":"2023-05-17T00:00:00+02:00","price":0.07},{"start":"2023-05-17T00:00:00+02:00","end":"2023-05-17T01:00:00+02:00","price":0.07},{"start":"2023-05-17T01:00:00+02:00","end":"2023-05-17T02:00:00+02:00","price":0.07},{"start":"2023-05-17T02:00:00+02:00","end":"2023-05-17T03:00:00+02:00","price":0.07},{"start":"2023-05-17T03:00:00+02:00","end":"2023-05-17T04:00:00+02:00","price":0.07},{"start":"2023-05-17T04:00:00+02:00","end":"2023-05-17T05:00:00+02:00","price":0.07},{"start":"2023-05-17T05:00:00+02:00","end":"2023-05-17T06:00:00+02:00","price":0.07},{"start":"2023-05-17T06:00:00+02:00","end":"2023-05-17T07:00:00+02:00","price":0.07},{"start":"2023-05-17T07:00:00+02:00","end":"2023-05-17T08:00:00+02:00","price":0.07},{"start":"2023-05-17T08:00:00+02:00","end":"2023-05-17T09:00:00+02:00","price":0.07},{"start":"2023-05-17T09:00:00+02:00","end":"2023-05-17T10:00:00+02:00","price":0.07},{"start":"2023-05-17T10:00:00+02:00","end":"2023-05-17T11:00:00+02:00","price":0.07},{"start":"2023-05-17T11:00:00+02:00","end":"2023-05-17T12:00:00+02:00","price":0.07},{"start":"2023-05-17T12:00:00+02:00","end":"2023-05-17T13:00:00+02:00","price":0.07},{"start":"2023-05-17T13:00:00+02:00","end":"2023-05-17T14:00:00+02:00","price":0.07},{"start":"2023-05-17T14:00:00+02:00","end":"2023-05-17T15:00:00+02:00","price":0.07},{"start":"2023-05-17T15:00:00+02:00","end":"2023-05-17T16:00:00+02:00","price":0.07},{"start":"2023-05-17T16:00:00+02:00","end":"2023-05-17T17:00:00+02:00","price":0.07},{"start":"2023-05-17T17:00:00+02:00","end":"2023-05-17T18:00:00+02:00","price":0.07},{"start":"2023-05-17T18:00:00+02:00","end":"2023-05-17T19:00:00+02:00","price":0.07},{"start":"2023-05-17T19:00:00+02:00","end":"2023-05-17T20:00:00+02:00","price":0.07},{"start":"2023-05-17T20:00:00+02:00","end":"2023-05-17T21:00:00+02:00","price":0.07},{"start":"2023-05-17T21:00:00+02:00","end":"2023-05-17T22:00:00+02:00","price":0.07},{"start":"2023-05-17T22:00:00+02:00","end":"2023-05-17T23:00:00+02:00","price":0.07},{"start":"2023-05-17T23:00:00+02:00","end":"2023-05-18T00:00:00+02:00","price":0.07},{"start":"2023-05-18T00:00:00+02:00","end":"2023-05-18T01:00:00+02:00","price":0.07},{"start":"2023-05-18T01:00:00+02:00","end":"2023-05-18T02:00:00+02:00","price":0.07},{"start":"2023-05-18T02:00:00+02:00","end":"2023-05-18T03:00:00+02:00","price":0.07},{"start":"2023-05-18T03:00:00+02:00","end":"2023-05-18T04:00:00+02:00","price":0.07},{"start":"2023-05-18T04:00:00+02:00","end":"2023-05-18T05:00:00+02:00","price":0.07},{"start":"2023-05-18T05:00:00+02:00","end":"2023-05-18T06:00:00+02:00","price":0.07},{"start":"2023-05-18T06:00:00+02:00","end":"2023-05-18T07:00:00+02:00","price":0.07},{"start":"2023-05-18T07:00:00+02:00","end":"2023-05-18T08:00:00+02:00","price":0.07},{"start":"2023-05-18T08:00:00+02:00","end":"2023-05-18T09:00:00+02:00","price":0.07},{"start":"2023-05-18T09:00:00+02:00","end":"2023-05-18T10:00:00+02:00","price":0.07},{"start":"2023-05-18T10:00:00+02:00","end":"2023-05-18T11:00:00+02:00","price":0.07},{"start":"2023-05-18T11:00:00+02:00","end":"2023-05-18T12:00:00+02:00","price":0.07},{"start":"2023-05-18T12:00:00+02:00","end":"2023-05-18T13:00:00+02:00","price":0.07},{"start":"2023-05-18T13:00:00+02:00","end":"2023-05-18T14:00:00+02:00","price":0.07},{"start":"2023-05-18T14:00:00+02:00","end":"2023-05-18T15:00:00+02:00","price":0.07},{"start":"2023-05-18T15:00:00+02:00","end":"2023-05-18T16:00:00+02:00","price":0.07},{"start":"2023-05-18T16:00:00+02:00","end":"2023-05-18T17:00:00+02:00","price":0.07},{"start":"2023-05-18T17:00:00+02:00","end":"2023-05-18T18:00:00+02:00","price":0.07},{"start":"2023-05-18T18:00:00+02:00","end":"2023-05-18T19:00:00+02:00","price":0.07},{"start":"2023-05-18T19:00:00+02:00","end":"2023-05-18T20:00:00+02:00","price":0.07},{"start":"2023-05-18T20:00:00+02:00","end":"2023-05-18T21:00:00+02:00","price":0.07},{"start":"2023-05-18T21:00:00+02:00","end":"2023-05-18T22:00:00+02:00","price":0.07},{"start":"2023-05-18T22:00:00+02:00","end":"2023-05-18T23:00:00+02:00","price":0.07},{"start":"2023-05-18T23:00:00+02:00","end":"2023-05-19T00:00:00+02:00","price":0.07},{"start":"2023-05-19T00:00:00+02:00","end":"2023-05-19T01:00:00+02:00","price":0.07},{"start":"2023-05-19T01:00:00+02:00","end":"2023-05-19T02:00:00+02:00","price":0.07},{"start":"2023-05-19T02:00:00+02:00","end":"2023-05-19T03:00:00+02:00","price":0.07},{"start":"2023-05-19T03:00:00+02:00","end":"2023-05-19T04:00:00+02:00","price":0.07},{"start":"2023-05-19T04:00:00+02:00","end":"2023-05-19T05:00:00+02:00","price":0.07},{"start":"2023-05-19T05:00:00+02:00","end":"2023-05-19T06:00:00+02:00","price":0.07},{"start":"2023-05-19T06:00:00+02:00","end":"2023-05-19T07:00:00+02:00","price":0.07},{"start":"2023-05-19T07:00:00+02:00","end":"2023-05-19T08:00:00+02:00","price":0.07},{"start":"2023-05-19T08:00:00+02:00","end":"2023-05-19T09:00:00+02:00","price":0.07},{"start":"2023-05-19T09:00:00+02:00","end":"2023-05-19T10:00:00+02:00","price":0.07},{"start":"2023-05-19T10:00:00+02:00","end":"2023-05-19T11:00:00+02:00","price":0.07},{"start":"2023-05-19T11:00:00+02:00","end":"2023-05-19T12:00:00+02:00","price":0.07},{"start":"2023-05-19T12:00:00+02:00","end":"2023-05-19T13:00:00+02:00","price":0.07},{"start":"2023-05-19T13:00:00+02:00","end":"2023-05-19T14:00:00+02:00","price":0.07},{"start":"2023-05-19T14:00:00+02:00","end":"2023-05-19T15:00:00+02:00","price":0.07},{"start":"2023-05-19T15:00:00+02:00","end":"2023-05-19T16:00:00+02:00","price":0.07},{"start":"2023-05-19T16:00:00+02:00","end":"2023-05-19T17:00:00+02:00","price":0.07},{"start":"2023-05-19T17:00:00+02:00","end":"2023-05-19T18:00:00+02:00","price":0.07},{"start":"2023-05-19T18:00:00+02:00","end":"2023-05-19T19:00:00+02:00","price":0.07},{"start":"2023-05-19T19:00:00+02:00","end":"2023-05-19T20:00:00+02:00","price":0.07},{"start":"2023-05-19T20:00:00+02:00","end":"2023-05-19T21:00:00+02:00","price":0.07},{"start":"2023-05-19T21:00:00+02:00","end":"2023-05-19T22:00:00+02:00","price":0.07},{"start":"2023-05-19T22:00:00+02:00","end":"2023-05-19T23:00:00+02:00","price":0.07},{"start":"2023-05-19T23:00:00+02:00","end":"2023-05-20T00:00:00+02:00","price":0.07},{"start":"2023-05-20T00:00:00+02:00","end":"2023-05-20T01:00:00+02:00","price":0.07},{"start":"2023-05-20T01:00:00+02:00","end":"2023-05-20T02:00:00+02:00","price":0.07},{"start":"2023-05-20T02:00:00+02:00","end":"2023-05-20T03:00:00+02:00","price":0.07},{"start":"2023-05-20T03:00:00+02:00","end":"2023-05-20T04:00:00+02:00","price":0.07},{"start":"2023-05-20T04:00:00+02:00","end":"2023-05-20T05:00:00+02:00","price":0.07},{"start":"2023-05-20T05:00:00+02:00","end":"2023-05-20T06:00:00+02:00","price":0.07},{"start":"2023-05-20T06:00:00+02:00","end":"2023-05-20T07:00:00+02:00","price":0.07},{"start":"2023-05-20T07:00:00+02:00","end":"2023-05-20T08:00:00+02:00","price":0.07},{"start":"2023-05-20T08:00:00+02:00","end":"2023-05-20T09:00:00+02:00","price":0.07},{"start":"2023-05-20T09:00:00+02:00","end":"2023-05-20T10:00:00+02:00","price":0.07},{"start":"2023-05-20T10:00:00+02:00","end":"2023-05-20T11:00:00+02:00","price":0.07},{"start":"2023-05-20T11:00:00+02:00","end":"2023-05-20T12:00:00+02:00","price":0.07},{"start":"2023-05-20T12:00:00+02:00","end":"2023-05-20T13:00:00+02:00","price":0.07},{"start":"2023-05-20T13:00:00+02:00","end":"2023-05-20T14:00:00+02:00","price":0.07},{"start":"2023-05-20T14:00:00+02:00","end":"2023-05-20T15:00:00+02:00","price":0.07},{"start":"2023-05-20T15:00:00+02:00","end":"2023-05-20T16:00:00+02:00","price":0.07},{"start":"2023-05-20T16:00:00+02:00","end":"2023-05-20T17:00:00+02:00","price":0.07},{"start":"2023-05-20T17:00:00+02:00","end":"2023-05-20T18:00:00+02:00","price":0.07},{"start":"2023-05-20T18:00:00+02:00","end":"2023-05-20T19:00:00+02:00","price":0.07},{"start":"2023-05-20T19:00:00+02:00","end":"2023-05-20T20:00:00+02:00","price":0.07},{"start":"2023-05-20T20:00:00+02:00","end":"2023-05-20T21:00:00+02:00","price":0.07},{"start":"2023-05-20T21:00:00+02:00","end":"2023-05-20T22:00:00+02:00","price":0.07},{"start":"2023-05-20T22:00:00+02:00","end":"2023-05-20T23:00:00+02:00","price":0.07},{"start":"2023-05-20T23:00:00+02:00","end":"2023-05-21T00:00:00+02:00","price":0.07},{"start":"2023-05-21T00:00:00+02:00","end":"2023-05-21T01:00:00+02:00","price":0.07},{"start":"2023-05-21T01:00:00+02:00","end":"2023-05-21T02:00:00+02:00","price":0.07},{"start":"2023-05-21T02:00:00+02:00","end":"2023-05-21T03:00:00+02:00","price":0.07},{"start":"2023-05-21T03:00:00+02:00","end":"2023-05-21T04:00:00+02:00","price":0.07},{"start":"2023-05-21T04:00:00+02:00","end":"2023-05-21T05:00:00+02:00","price":0.07},{"start":"2023-05-21T05:00:00+02:00","end":"2023-05-21T06:00:00+02:00","price":0.07},{"start":"2023-05-21T06:00:00+02:00","end":"2023-05-21T07:00:00+02:00","price":0.07},{"start":"2023-05-21T07:00:00+02:00","end":"2023-05-21T08:00:00+02:00","price":0.07},{"start":"2023-05-21T08:00:00+02:00","end":"2023-05-21T09:00:00+02:00","price":0.07},{"start":"2023-05-21T09:00:00+02:00","end":"2023-05-21T10:00:00+02:00","price":0.07},{"start":"2023-05-21T10:00:00+02:00","end":"2023-05-21T11:00:00+02:00","price":0.07},{"start":"2023-05-21T11:00:00+02:00","end":"2023-05-21T12:00:00+02:00","price":0.07},{"start":"2023-05-21T12:00:00+02:00","end":"2023-05-21T13:00:00+02:00","price":0.07},{"start":"2023-05-21T13:00:00+02:00","end":"2023-05-21T14:00:00+02:00","price":0.07},{"start":"2023-05-21T14:00:00+02:00","end":"2023-05-21T15:00:00+02:00","price":0.07},{"start":"2023-05-21T15:00:00+02:00","end":"2023-05-21T16:00:00+02:00","price":0.07},{"start":"2023-05-21T16:00:00+02:00","end":"2023-05-21T17:00:00+02:00","price":0.07},{"start":"2023-05-21T17:00:00+02:00","end":"2023-05-21T18:00:00+02:00","price":0.07},{"start":"2023-05-21T18:00:00+02:00","end":"2023-05-21T19:00:00+02:00","price":0.07},{"start":"2023-05-21T19:00:00+02:00","end":"2023-05-21T20:00:00+02:00","price":0.07},{"start":"2023-05-21T20:00:00+02:00","end":"2023-05-21T21:00:00+02:00","price":0.07},{"start":"2023-05-21T21:00:00+02:00","end":"2023-05-21T22:00:00+02:00","price":0.07},{"start":"2023-05-21T22:00:00+02:00","end":"2023-05-21T23:00:00+02:00","price":0.07},{"start":"2023-05-21T23:00:00+02:00","end":"2023-05-22T00:00:00+02:00","price":0.07},{"start":"2023-05-22T00:00:00+02:00","end":"2023-05-22T01:00:00+02:00","price":0.07},{"start":"2023-05-22T01:00:00+02:00","end":"2023-05-22T02:00:00+02:00","price":0.07},{"start":"2023-05-22T02:00:00+02:00","end":"2023-05-22T03:00:00+02:00","price":0.07},{"start":"2023-05-22T03:00:00+02:00","end":"2023-05-22T04:00:00+02:00","price":0.07},{"start":"2023-05-22T04:00:00+02:00","end":"2023-05-22T05:00:00+02:00","price":0.07},{"start":"2023-05-22T05:00:00+02:00","end":"2023-05-22T06:00:00+02:00","price":0.07},{"start":"2023-05-22T06:00:00+02:00","end":"2023-05-22T07:00:00+02:00","price":0.07},{"start":"2023-05-22T07:00:00+02:00","end":"2023-05-22T08:00:00+02:00","price":0.07},{"start":"2023-05-22T08:00:00+02:00","end":"2023-05-22T09:00:00+02:00","price":0.07},{"start":"2023-05-22T09:00:00+02:00","end":"2023-05-22T10:00:00+02:00","price":0.07},{"start":"2023-05-22T10:00:00+02:00","end":"2023-05-22T11:00:00+02:00","price":0.07},{"start":"2023-05-22T11:00:00+02:00","end":"2023-05-22T12:00:00+02:00","price":0.07},{"start":"2023-05-22T12:00:00+02:00","end":"2023-05-22T13:00:00+02:00","price":0.07},{"start":"2023-05-22T13:00:00+02:00","end":"2023-05-22T14:00:00+02:00","price":0.07},{"start":"2023-05-22T14:00:00+02:00","end":"2023-05-22T15:00:00+02:00","price":0.07},{"start":"2023-05-22T15:00:00+02:00","end":"2023-05-22T16:00:00+02:00","price":0.07},{"start":"2023-05-22T16:00:00+02:00","end":"2023-05-22T17:00:00+02:00","price":0.07},{"start":"2023-05-22T17:00:00+02:00","end":"2023-05-22T18:00:00+02:00","price":0.07},{"start":"2023-05-22T18:00:00+02:00","end":"2023-05-22T19:00:00+02:00","price":0.07},{"start":"2023-05-22T19:00:00+02:00","end":"2023-05-22T20:00:00+02:00","price":0.07},{"start":"2023-05-22T20:00:00+02:00","end":"2023-05-22T21:00:00+02:00","price":0.07},{"start":"2023-05-22T21:00:00+02:00","end":"2023-05-22T22:00:00+02:00","price":0.07},{"start":"2023-05-22T22:00:00+02:00","end":"2023-05-22T23:00:00+02:00","price":0.07},{"start":"2023-05-22T23:00:00+02:00","end":"2023-05-23T00:00:00+02:00","price":0.07}]}}`

Wie soll sowas in ioBroker abgebildet werden??

**Comment by Marty56** [comment]
Ja, dass wäre wirklich super. 
Mit jq ist dir Nutzung in iobroker dann total einfach.

**Comment by Marty56** [comment]
Einfach als JSON Datenpunkt

**Comment by Marty56** [comment]
Ich habe bemerkt, dass es auch den Adapter Tibber connect gibt.
Damit lässen sich die Daten auch abholen. Insofern für mich nicht mehr ganz so wichtig.

**Comment by Newan** [comment]
PR merged
