### ISSUE TITLE
Datenpunkte mit ACK bzw Button

### ISSUE THREAD

**Issue by SKB-CGN** [Newan/ioBroker.evcc#22]
Hi,
der Adapter funktioniert erstmal super.

Baust Du noch die ack für die states ein bzw. das der Button wieder zurückspringt, wenn er gedrückt wurde?

Dies ist bei dem control-Baum schöner, denke ich, wenn man sieht, was aktiv ist.

Gibt es auch einen Datenpunkt, der mitteilt, welcher Modus aktiv ist?

Ich habe den Punkt "mode" gefunden, der sagt allerdings "off", obwohl EVCC auf "PV" steht.

**Comment by Newan** [comment]
pls testen der neuesten Version, dafür bitte einmal den Objektbaum komplett löschen
