### ISSUE TITLE
evcc 0.123.x update

### ISSUE THREAD

**Issue by gz2k2** [Newan/ioBroker.evcc#23]
**Describe the bug**  
Seit dem evcc 0.123.x Update funktioniert der Adapter nicht mehr richtig.

**To Reproduce**  
evcc 0.123.x installieren und mit dem Adapter verbiden

**Expected behavior**  
Einige Datenpunkte funktionieren nicht mehr

**Screenshots & Logfiles**  
![grafik](https://github.com/Newan/ioBroker.evcc/assets/77876301/2aaa880e-8233-4999-a18c-63e0ebcf81e5)

**Comment by Newan** [comment]
Kommen den log Einträge mit Fehlern?

**Comment by gz2k2** [comment]
Nein, Fehler sind keine im Log.
Wenn ich z.B. in den Datenpunkt "evcc.0.loadpoint.1.control.targetSoc" einen Wert schreibe, ändert es in evcc nichts mehr seit v0.123.x.
Ich habe parallel auch noch die MQTT Anbindung am laufen. Da kann ich Werte ändern und es funktioniert ohne Probleme.

Evtl. hat es auch damit zu tun:
https://github.com/evcc-io/evcc/issues/11243

**Comment by Newan** [comment]
Ja die API wurde generell nun anders aufgebaut. Da brauch ich echt Zeit für. Den das bedeutet das ich den Adapter Grundlgend neu machen darf.
Aber werde ich machen!

**Comment by Newan** [comment]
pls testen der neuesten Version, dafür bitte einmal den Objektbaum komplett löschen

**Comment by gz2k2** [comment]
Funktioniert soweit alles. nur die Lademodi sind keine Schalter mehr.
Muss sie immer auf true/false setzten. aber der Lademodus wird in evcc geändert.

![grafik](https://github.com/Newan/ioBroker.evcc/assets/77876301/bc2275e1-446f-42a3-a3f9-cd63647caee9)

**Comment by gz2k2** [comment]
kannst Du noch einbauen, dass man diese states ändern kann? per mqtt kann man die ändern:
![grafik](https://github.com/Newan/ioBroker.evcc/assets/77876301/0f8f95fd-426a-4501-9cb2-97567172c41d)

**Comment by Newan** [comment]
> kannst Du noch einbauen, dass man diese states ändern kann? per mqtt kann man die ändern: ![grafik](https://private-user-images.githubusercontent.com/77876301/293478387-0f8f95fd-426a-4501-9cb2-97567172c41d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5Njc1ODMsIm5iZiI6MTcwMzk2NzI4MywicGF0aCI6Ii83Nzg3NjMwMS8yOTM0NzgzODctMGY4Zjk1ZmQtNDI2YS00NTAxLTljYjItOTc1NjcxNzJjNDFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDIwMTQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxZGU5NjkxODFlNGUzOWRiN2FmNTJkNWFmYjg2ZDFjYWQ4NWJiMWY0MTU2NWRjNWNkNTgwMjcwMjg4MjEzMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p8cNUlr4nDPO7IEcyNHuAqTm97hu_HZd4E4SPe-TWF8)

Muss die Funktion in der web Oberfläche haben, dann kann ich es nachbauen

**Comment by Newan** [comment]
> Funktioniert soweit alles. nur die Lademodi sind keine Schalter mehr. Muss sie immer auf true/false setzten. aber der Lademodus wird in evcc geändert.
> 
> ![grafik](https://private-user-images.githubusercontent.com/77876301/293478193-bc2275e1-446f-42a3-a3f9-cd63647caee9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5NzAxNDUsIm5iZiI6MTcwMzk2OTg0NSwicGF0aCI6Ii83Nzg3NjMwMS8yOTM0NzgxOTMtYmMyMjc1ZTEtNDQ2Zi00MmEzLWEzZjktY2Q2MzY0N2NhZWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDIwNTcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljOGU3MzI4YmU1YWE2Y2NhMmU3NzQ3ZmRiNzM5ZDI3YzJjNTUyYjllMWUwOThjYjI1OTg4ZTBmY2UyYmI3YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JAoMwdr5TjJczTKjrZWfdeP9ORadYdEsxYZwziwmgz8)

Expertenmodus aus, da sind Buttons :-)

**Comment by gz2k2** [comment]
> > kannst Du noch einbauen, dass man diese states ändern kann? per mqtt kann man die ändern: ![grafik](https://private-user-images.githubusercontent.com/77876301/293478387-0f8f95fd-426a-4501-9cb2-97567172c41d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5Njc1ODMsIm5iZiI6MTcwMzk2NzI4MywicGF0aCI6Ii83Nzg3NjMwMS8yOTM0NzgzODctMGY4Zjk1ZmQtNDI2YS00NTAxLTljYjItOTc1NjcxNzJjNDFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDIwMTQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxZGU5NjkxODFlNGUzOWRiN2FmNTJkNWFmYjg2ZDFjYWQ4NWJiMWY0MTU2NWRjNWNkNTgwMjcwMjg4MjEzMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p8cNUlr4nDPO7IEcyNHuAqTm97hu_HZd4E4SPe-TWF8)
> 
> Muss die Funktion in der web Oberfläche haben, dann kann ich es nachbauen

in der Web oberfläche ist sie hier: 

![grafik](https://github.com/Newan/ioBroker.evcc/assets/77876301/4f105bf1-758c-4160-a8c4-95c3cffe99d3)

**Comment by Newan** [comment]
Welcher Speicher ist das den? Sorry die Funktion hab ich mit Fronius und BYD nicht gesehen bisher!

**Comment by Newan** [comment]
Gefunden, aber noch nicht verstanden :-) .. lese mich ein

**Comment by gz2k2** [comment]
> Gefunden, aber noch nicht verstanden :-) .. lese mich ein

hier stellt man ein, ab wieviel Ladestand der Hausbatterie das Auto das Laden im PV-Modus anfängt. Bei mir im Beispielt wird die Hausbatterie vorrangig erst auf 50% geladen, dann darf das Fahrzeug laden. Und bei 96% Ladestand wird auch die energie aus der Batterie zum autoladen verwendet

**Comment by Newan** [comment]
Bitte letzten commit testen!

**Comment by gz2k2** [comment]
> Bitte letzten commit testen!

Funktioniert! Super, Danke! :)
