### ISSUE TITLE
Wie wird der EVCC Adapter in IOBroker installiert?

### ISSUE THREAD

**Issue by mhibu** [Newan/ioBroker.evcc#3]
Habe das aktuelle Image im Expertenmodus ausgeführt:

Installing /home/pi/ioBroker.evcc-0.0.5.tar.gz... (System call)

npm WARN crc@4.1.1 requires a peer of buffer@>=6.0.3 but none is installed. You must install peer dependencies yourself.

npm WARN winston-syslog@2.7.0 requires a peer of winston@^3.8.2 but none is installed. You must install peer dependencies yourself.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

+ iobroker.evcc@0.0.5updated 1 package in 21.685s

62 packages are looking for funding run `npm fund` for details

upload [11] evcc.admin /opt/iobroker/node_modules/iobroker.evcc/admin/evcc.png evcc.png image/png

upload [10] evcc.admin /opt/iobroker/node_modules/iobroker.evcc/admin/i18n/de/translations.json i18n/de/translations.json application/json

upload [2] evcc.admin /opt/iobroker/node_modules/iobroker.evcc/admin/i18n/ru/translations.json i18n/ru/translations.json application/json

upload [0] evcc.admin /opt/iobroker/node_modules/iobroker.evcc/admin/jsonConfig.json jsonConfig.json application/json

Process exited with code 0

Im Anschluss wird keine Instanz angezeigt und es ist ein leerer Objekt Ordner eingetragen.
Was ist weiterhin zu tun?

Danke Michael

**Comment by Newan** [comment]
Über Adapter dann Github und dann evcc auswählen.
Es sit noch nicht im Stable repo sondern nur im latest
