### ISSUE TITLE
evcc Host wird nicht gefunden (Dokumentation)

### ISSUE THREAD

**Issue by escuco** [Newan/ioBroker.evcc#6]
Hallo!

Ich bin per Zufall auf diesen interessanten Adapter gestoßen. Die Installation lief ohne Probleme (per Github URL), allerdings bekomme ich keine Verbindung zu evcc.

Aus dem iobroker log:
`connect EHOSTUNREACH 192.168.2.100:7070`

IP und Port sind korrekt, evcc läuft einwandfrei. Objekte sind in iobroker vorhanden, stehen natürlich alle auf "false". Was könnte das sein?

evcc v0111.1
ioBroker.evcc v0.0.7

Und in dem Zusammenhang: Gibt es irgendwo eine Dokumentation/Thread zu diesem Adapter?

**Comment by Newan** [comment]
https://forum.iobroker.net/topic/49165/neuer-adapter-iobroker-evcc
