### ISSUE TITLE
Ändern von "threshold" über Datenpunkt

### ISSUE THREAD

**Issue by Marty56** [Newan/ioBroker.evcc#9]
**Describe the change**  
Es wäre schön, wenn man diese evcc Parameter ändern könnte

POST /api/loadpoints/<id>/enable/threshold/<threshold>: threshold value in W
POST /api/loadpoints/<id>/disable/threshold/<threshold>: threshold value in W

Hintergrund:
Im Winter hat man andere Werte als im Sommer.

**Comment by Newan** [comment]
Ja baue ich gerne ein, aber bitte erkläre mal welche Werte sich da im Winter ändern?

**Comment by Marty56** [comment]
Hallo Newan,
Ich verstehe jetzt selber nicht, was ich da geschrieben habe.
Mein Verständnis ist, dass das jetzt schon möglich ist. Meine Erklärung für mein Post ist jetzt, dass ich es versucht habe und es nicht funktioniert hat, aber nur weil ich statt "/" "//" geschrieben hatte.

Und zum Use Case.
Ich habe eine kleine PV Anlage und will, dass sie innerhalb eines Zeitraum, z.B. einen Tag, mein Auto auf einen bestimmten Ladestand bringt. Je nach PV Einstrahlung muss ich also mehr oder weniger Netzstrom zu lassen. Das will ich so realisieren, dass ich jede Stunde residual Power ändere, was dann eine Änderung der thresholds nach sich zieht.

Aber vielleicht gibt es dafür auch eine einfachere Lösung. Ich hatte schon an pvmin gedacht, aber das funktioniert nicht, weil öfters mehr Strom erzeugen kann, als mit pvmin ins Auto geliefert wird.
